### ISSUE TITLE
New Bundles for Test

### ISSUE THREAD

**Issue by JPH71** [acvigue/pgma#5] opened 2019-10-12 08:49 UTC
Hi Aiden

As promised, here are the bundles I have scripted/amended.
All videos should be in format (studio name) - Movie Title (Year).ext; I stuck with this as many pornographic movies share the same titles across various studios

I have set the background art to the back cover of the dvd as default.

one issue with gayhotmovies is that if the search return comes back with a result on the 2nd page... it does not pick it up... I havent figured a way to parse through all the search results.. And I can no longer rememeber the movie I was trying to scrap... grrr...

I have tested waybig against MenAtPlay and TimTales. Waybig.com seemed to be the only place where I could find TimTales posters.

One issue I have noticed is that sometimes the update function does not kick in... I have a feeling it has got something to do with scoring. But as i stick to the naming convention the only time a search is sucessfull is if the naming format follows the standards and the search finds it on a site, so the score is always 100% when it gets to this point.

Please let me know of anything that I have done wrong, this is the first time I have ever scripted in Python and I know I could have done some things more efficiently.

[Porn bundles.zip](https://github.com/acvigue/pgma/files/3720398/Porn.bundles.zip)

**Comment by CodyBerenson** [comment] 2019-11-22 00:48
JPH71:  Thanks so much!  This is really working fantastic for me.  Love that you've connected AEBN (and the others) with pulling the actor art from IAFD.  I'm not sure if you want specific feedback if I run into any issues, but wanted to tell you how much I appreciate your efforts.  Cheers!

**Comment by acvigue** [comment] 2019-11-22 01:48
hey, sorry. i've been really busy the past few weeks. i'll clean these up and add them. format will be changed to *Movie title (year -optional).ext bc of existing conventions.

**Comment by CodyBerenson** [comment] 2019-11-30 00:01
JPH71:  Since the full-movie indexes work so great, i started to index my clips on WayBig.com since they have cover art, actors, and description as you mention.  The agent is hit or miss, and I can't pinpoint a pattern.  It seems that commas are an issue, and sometimes single quotes.  Not sure you're checking the thread or have any interest in trouble shooting, but i just wanted to mention. And, truly, thanks again for the other agents.  They work terrific.

**Comment by JPH71** [comment] 2019-11-30 08:45
I will start checking the thread and trouble shooting...
I need to get both my skills in python and web scrapping up to scratch.
At the moment I am working on homoactive...

**Comment by JPH71** [comment] 2019-11-30 08:46
One question on the agents I have being working on... Plex does not seem to
recognise duplicates...

**Comment by CodyBerenson** [comment] 2019-11-30 17:19
Duplicates in what sense?  Not sure I understand.  

Here's my experience with Plex and duplicates.  There are instances where i have an old .avi low quality and drop a HQ .mp4 *or* only had a scenes or two for a movie and not the entire movie (the already existing AEBN handles scenes fine (i.e. title scene x.mp4)).  sometime later i get a better quality of the full movie, drop it into plex, and plex auto combines it as a duplicate with the already existing movie or scene. I am then able to delete the  older movie or scene (if its of equal or less quality than the movie).  
Anyway...

Waybig examples that work and don't for your trouble-shooting.  As you can see, without being a techie with log files it isn't visually consistent why some titles work and others do not.  lol.  Thanks!

Works:
(Bromo) - Man Meat (Rico Fatale Barebacks Alex Morgan) (2018).mp4
(Bromo) - Blake Ryder Fucks Brendan Patrick in ‘Tied And Teased’ (2019).mp4
(Bromo) - Darin Silvers Fucks Daxx Carter in ‘Cellmates, Part 2’ (2019).mp4

Does not:
(Bromo) - Electric Sex, Part 1 (Rikk York Fucks Jay Austin) (2018).mp4
(Bromo) - Eddie Danger Fucks Eli Hunter in ‘Raw Tow Service, Part 3’ (2019).mp4
(Bromo) - Zane Stone Fucks Draven Navarro in ‘Lords of RAW-Dog, Part 2’ (2018).mp4

You rock, buddy!

**Comment by acvigue** [comment] 2019-11-30 18:13
I'm going to go ahead and place these agents in the master branch. Would you like me to take a look at how to better match with Waybig?

**Comment by CodyBerenson** [comment] 2019-11-30 20:51
:)  please!  and THANK YOU!

**Comment by fabutrash** [comment] 2019-11-30 22:34
@acvigue thank you for adding this to the master branch. I wouldn't know where to start with the scrapers and whatnot. I still can't get any of my videos to match but will persist xoxo

**Comment by acvigue** [comment] 2019-12-01 18:44
could you zip your logs and create a new issue please?

**Comment by acvigue** [comment] 2019-12-01 18:45
this issue will be CLOSED as the primary intent was to add new bundles and that has been accomplished. any further comments on this can be moved to a new issue.

**Closed by acvigue** 2019-12-01 18:45 UTC
Labels: enhancement, in-progress

**Comment by JPH71** [comment] 2019-12-01 20:47
Hi Aiden and Cody

Duplicates in this sense

(Studio) - Movie name (year).avi
(Studio) - Movie name (year).mp4

I get (two entries) instead of (one with the number 2 showing up in blue in
the top right corner)...

I have also made a change to the gayhotmovies scrapper as it was not
finding movies with an "&" in the title. So I now replace "& " with "" in
the search..
Testing this change at the moment...
I will upload this to the site soon...

Kind regards and thanks for all your help with the scrapping...
At the moment trying to sort out homoactiv, will upload this one soon.

**Comment by JPH71** [comment] 2019-12-01 20:49
if you know of any sites like aebn, gayhotmovies and gaydvdmovies that
could benefit from scrapping let me know.
I have some free time coming up :)

**Comment by CodyBerenson** [comment] 2019-12-02 03:46
JPH:

re: duplicates:  the functionality for me isn't as you describe.  it combines and give the blue lable in the upper left corner.

re: additional sites, those sites work well for me....gets the largest % of the feature flicks;  the few exceptions I don't mind creating xml for.  Lots of people ask for an index for gayeroticvideoindex.com  If such a scraper existed, that could get the covers and get actor images from  IAFD....now THAT would be a terrific index.  LOL.  

OK, on my wish list for your free time coming up would be to figure out why waybig.com is so hit or miss.  I gave several good test cases above.  could offer more if its helpful.  Sometimes clips with "," work, sometime not.  Sometimes "&" work but more often not.   

ACVIGUE:  You asked if we'd like you to look into waybig.com, and then changed this thread to enhancement.  I'm confused, are you asking me to attach logs or are you asking fabutrash?  Are you asking that all further discussions be added to a new issue..or..?   Your hosting this and all that you do is truly appreciated.

**Comment by acvigue** [comment] 2019-12-02 03:56
what i meant was that all further conversation about the agents such as the WAYBIG one should be moved to a different issue because if anyone else searches for an issue they are having with waybig, it would be more likely they would click on an issue called “waybig agent not matching all the time” rather than “new bundles for test.” sorry for the confusion. 😂 What i meant by enhancement was that these new bundles enhanced the original code base, nothing else was intended 😃

**Comment by CodyBerenson** [comment] 2019-12-02 04:04
got it.  i'll open it now.  thanks for your patience.  I'll open a new issue.  You all are fantastic.  thanks!  :)

**Comment by JPH71** [comment] 2019-12-22 23:41
Hi All

Waybig.com changed its website ever so slightly a fortnight or so ago and
none of my TimTales would scrape..
I have made the necessary changes and its now working.
Here is the code for testing.

**Comment by JPH71** [comment] 2019-12-23 13:48
Waybig seems rather haphazard with its results especially if there 's a " '
" in any of the words....
I at first tried stripping all words with the apostrophe in it... didn't
work consistently...
in the midst of this testing it seems that waybig starts to falter if the
search string has more than 9 separate words.
I have ended up by splitting the serach string at the first apostrophe and
also made a correction to the Lists of Titles being returned...
This seems to have sorted out the issue...

**Comment by CodyBerenson** [comment] 2019-12-27 15:50
Did you upload code?  I'm confused.  Happens easily.  :)

**Comment by JPH71** [comment] 2019-12-30 22:39
It was attached to the email.
I still have not figured how to upload files...

**Comment by JPH71** [comment] 2019-12-30 22:42
here are the bundles for Gay Erotic Video Index (GEVI) ... tested it on 78
Triga Film Titles and it found 75
also attached is the Waybig.bundle just in case

**Comment by CodyBerenson** [comment] 2020-01-01 22:16
happy new year!  I don't mean to be difficult, but there are no attachments???  in the very first post of this thread, you uploaded a zip....if you're replying to the email, that isn't going to work I don't think.
here's the github link for acvigue's repository, and the specific issue that you started before.  

https://github.com/acvigue/pgma/issues/5

**Comment by JPH71** [comment] 2020-01-02 00:11
How does one upload to this site then?

**Comment by JPH71** [comment] 2020-01-02 00:46
I have uploaded the new bundles by creating a new issue and attaching them
to it...
